# Generated by Django 6.0.6 on 2026-07-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_image_carimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='speed',
            field=models.CharField(blank=True, help_text='Example: 3.2s 0-100 km/h', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='Automatic', max_length=50),
        ),
    ]
