# Generated by Django 6.0.6 on 2026-07-11 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_body_type_car_engine_car_speed_car_transmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='engine',
        ),
        migrations.RemoveField(
            model_name='car',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='car',
            name='transmission',
        ),
    ]
