# Generated by Django 6.0.6 on 2026-07-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='interest',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
