# Generated by Django 6.0.6 on 2026-07-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('engine', 'Engine'), ('brake', 'Brake'), ('electrical', 'Electrical'), ('body', 'Body'), ('interior', 'Interior'), ('other', 'Other')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('compatibility', models.CharField(help_text='Example: Toyota Corolla 2018-2023', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='parts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
